services:
  - type: web
    name: recibos-aluguel
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@exemplo.com
      - key: ADMIN_PASSWORD
        value: mudeEstaSenha123
      - key: DATABASE_URL
        sync: false
